// Code generated by protoc-gen-go. DO NOT EDIT.
// source: null.proto

package null

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Int struct {
	Int64                int64    `protobuf:"varint,1,opt,name=Int64,proto3" json:"Int64,omitempty"`
	Valid                bool     `protobuf:"varint,2,opt,name=Valid,proto3" json:"Valid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Int) Reset()         { *m = Int{} }
func (m *Int) String() string { return proto.CompactTextString(m) }
func (*Int) ProtoMessage()    {}
func (*Int) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf5db73f817afc81, []int{0}
}

func (m *Int) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Int.Unmarshal(m, b)
}
func (m *Int) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Int.Marshal(b, m, deterministic)
}
func (m *Int) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Int.Merge(m, src)
}
func (m *Int) XXX_Size() int {
	return xxx_messageInfo_Int.Size(m)
}
func (m *Int) XXX_DiscardUnknown() {
	xxx_messageInfo_Int.DiscardUnknown(m)
}

var xxx_messageInfo_Int proto.InternalMessageInfo

func (m *Int) GetInt64() int64 {
	if m != nil {
		return m.Int64
	}
	return 0
}

func (m *Int) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

type Bool struct {
	Bool                 bool     `protobuf:"varint,1,opt,name=Bool,proto3" json:"Bool,omitempty"`
	Valid                bool     `protobuf:"varint,2,opt,name=Valid,proto3" json:"Valid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Bool) Reset()         { *m = Bool{} }
func (m *Bool) String() string { return proto.CompactTextString(m) }
func (*Bool) ProtoMessage()    {}
func (*Bool) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf5db73f817afc81, []int{1}
}

func (m *Bool) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Bool.Unmarshal(m, b)
}
func (m *Bool) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Bool.Marshal(b, m, deterministic)
}
func (m *Bool) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Bool.Merge(m, src)
}
func (m *Bool) XXX_Size() int {
	return xxx_messageInfo_Bool.Size(m)
}
func (m *Bool) XXX_DiscardUnknown() {
	xxx_messageInfo_Bool.DiscardUnknown(m)
}

var xxx_messageInfo_Bool proto.InternalMessageInfo

func (m *Bool) GetBool() bool {
	if m != nil {
		return m.Bool
	}
	return false
}

func (m *Bool) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

func init() {
	proto.RegisterType((*Int)(nil), "null.Int")
	proto.RegisterType((*Bool)(nil), "null.Bool")
}

func init() { proto.RegisterFile("null.proto", fileDescriptor_bf5db73f817afc81) }

var fileDescriptor_bf5db73f817afc81 = []byte{
	// 105 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xca, 0x2b, 0xcd, 0xc9,
	0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x01, 0xb1, 0x95, 0x0c, 0xb9, 0x98, 0x3d, 0xf3,
	0x4a, 0x84, 0x44, 0xb8, 0x58, 0x3d, 0xf3, 0x4a, 0xcc, 0x4c, 0x24, 0x18, 0x15, 0x18, 0x35, 0x98,
	0x83, 0x20, 0x1c, 0x90, 0x68, 0x58, 0x62, 0x4e, 0x66, 0x8a, 0x04, 0x93, 0x02, 0xa3, 0x06, 0x47,
	0x10, 0x84, 0xa3, 0x64, 0xc0, 0xc5, 0xe2, 0x94, 0x9f, 0x9f, 0x23, 0x24, 0x04, 0xa1, 0xc1, 0x5a,
	0x38, 0x82, 0x20, 0x62, 0x58, 0x75, 0x24, 0xb1, 0x81, 0x6d, 0x34, 0x06, 0x04, 0x00, 0x00, 0xff,
	0xff, 0xa9, 0x06, 0x4c, 0x56, 0x7f, 0x00, 0x00, 0x00,
}
